### ISSUE TITLE
Insta Icon not showing

### ISSUE THREAD

**Issue by Chetan-Raut** [Kaushal-Dahekar/Kaushal-Portfolio#1]
![IMG_20230709_205224.jpg](https://github.com/Kaushal-Dahekar/Kaushal-Portfolio/assets/114333234/7cd2d484-eb54-470a-97da-f5a19582fd46)

_Change the Source of the image from Instagram.svg to instagram.svg_

**Comment by Kaushal-Dahekar** [comment]
_thanks_
